# Generated by Django 4.2.3 on 2024-07-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0027_telegrames_alter_ebcjiasushouyijilu_layer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrames',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '未生效'), (1, '已生效')], db_comment='0 未生效,1已生效', default=0, null=True),
        ),
    ]
