# Generated by Django 4.2.3 on 2024-07-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0028_alter_telegrames_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrames',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='telegrames',
            name='TelUserId',
            field=models.CharField(blank=True, db_comment='TelUserId', max_length=255, null=True, verbose_name='TelUserId'),
        ),
        migrations.AlterField(
            model_name='telegrames',
            name='TelUserName',
            field=models.CharField(blank=True, db_comment='TelUserName', max_length=255, null=True, verbose_name='TelUserName'),
        ),
        migrations.AlterField(
            model_name='telegrames',
            name='TelUserText',
            field=models.CharField(blank=True, db_comment='TelUserText', max_length=255, null=True, verbose_name='TelUserText'),
        ),
    ]
