# Generated by Django 4.2.3 on 2024-07-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0029_telegrames_created_at_alter_telegrames_teluserid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenzhiyajishi',
            name='amountShouYi',
            field=models.FloatField(blank=True, db_comment='质押收益', null=True, verbose_name='质押收益'),
        ),
    ]
