# Generated by Django 4.2.3 on 2024-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0030_customuser_tdallamount_customuser_tdxiaoquamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bestMaxKuangJi',
            field=models.FloatField(blank=True, db_comment='质押最大矿机', default=0, null=True, verbose_name='质押最大矿机'),
        ),
        migrations.AlterField(
            model_name='paytoken',
            name='Layer',
            field=models.IntegerField(blank=True, db_comment='1usdt 2 amt 3 amt', default=0, null=True, verbose_name='类型'),
        ),
    ]
