# Generated by Django 4.2.3 on 2024-07-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0031_customuser_bestmaxkuangji_alter_paytoken_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenzhiyajishi',
            name='dianJiCiShu',
            field=models.IntegerField(choices=[(0, '质押中'), (1, '已释放')], db_comment='被点击次数', default=0),
        ),
    ]
