# Generated by Django 4.2.3 on 2024-07-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0032_tokenzhiyajishi_dianjicishu'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selfYeJi',
            field=models.FloatField(blank=True, db_comment='个人投入', default=0, null=True, verbose_name='个人投入'),
        ),
    ]
