# Generated by Django 4.2.3 on 2024-07-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0033_customuser_selfyeji'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='TDallInAmount',
            field=models.FloatField(blank=True, db_comment='团队全部总值', default=0, null=True, verbose_name='团队全部总值'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='TDallAmount',
            field=models.FloatField(blank=True, db_comment='团队大区总值', default=0, null=True, verbose_name='团队总值'),
        ),
    ]
