# Generated by Django 4.2.3 on 2024-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0034_customuser_tdallinamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='TDallAmount',
            field=models.FloatField(blank=True, db_comment='团队大区总值', default=0, null=True, verbose_name='团队大区总值'),
        ),
    ]
