# Generated by Django 4.2.3 on 2024-08-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0035_alter_customuser_tdallamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tuanduiLevelName',
            field=models.CharField(blank=True, db_comment='团队等级名称', max_length=255, null=True, verbose_name='团队等级名称'),
        ),
    ]
