# Generated by Django 4.2.3 on 2024-09-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0036_customuser_tuanduilevelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userType',
            field=models.CharField(blank=True, db_comment='用户类型', max_length=255, null=True, verbose_name='用户类型'),
        ),
    ]
