# Generated by Django 4.2.3 on 2024-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0037_customuser_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='TuanDuiDaQuUser',
            field=models.CharField(blank=True, db_comment='团队大区用户', max_length=255, null=True, verbose_name='团队大区用户'),
        ),
    ]
