# Generated by Django 4.2.3 on 2024-09-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0038_customuser_tuanduidaquuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenzhiyajishi',
            name='dianJiCiShu',
            field=models.IntegerField(blank=True, db_comment='被点击次数', default=0, null=True),
        ),
    ]
