# Generated by Django 4.2.3 on 2024-10-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0039_alter_tokenzhiyajishi_dianjicishu'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='candyFanNum',
            field=models.IntegerField(blank=True, db_comment='已经发放直推数量', default=0, null=True),
        ),
    ]
