# Generated by Django 4.2.3 on 2024-10-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0040_customuser_candyfannum'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isOneToken',
            field=models.IntegerField(blank=True, db_comment='0 ,1 转出过cc', default=0, null=True),
        ),
    ]
