# Generated by Django 4.2.3 on 2024-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0041_customuser_isonetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebcjiasushouyijilu',
            name='Layer',
            field=models.IntegerField(blank=True, db_comment='0充值 1 代数 2 层数 3 #提现到账 日志 4.购买燃料包 等扣款 , 11.得到奖金池 ,21 2%加入奖金池 22 3%加入账户 ,30无矿机不分润', default=0, null=True, verbose_name='类型'),
        ),
    ]
