# Generated by Django 4.2.3 on 2024-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_alter_t_tokenaddr_last_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='jiangJinChiState',
            field=models.SmallIntegerField(blank=True, choices=[(1, '开'), (0, '关')], db_comment=' 奖金池开关', default=1, null=True, verbose_name='奖金池开关'),
        ),
    ]
